name: Java CI with Maven

# Trigger the workflow on push or pull request to main or feature branches
on:
  push:
    branches:
      - main
      - 'feature/*'
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up JDK 23
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23' # Updated to Java 23
          distribution: 'temurin' # Eclipse Temurin supports Java 23
          cache: 'maven' # Cache Maven dependencies

      # Install Google Chrome (required for Selenium tests)
      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          echo "deb http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update -y
          sudo apt-get install -y google-chrome-stable
          google-chrome --version

      # Build and run tests with Maven
      - name: Build and Test with Maven
        run: mvn clean test -B

      # Archive test reports for inspection
      - name: Archive Test Reports
        if: always() # Run even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/surefire-reports/